name: pr_check
on:
  pull_request:
    branches: main
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  deploy-shinyapps:
    name: pr_check_shinyapps
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
